---
title: "calibration with boostrap"
author: "kevin caye"
date: "14 fevrier 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

```{r}
library(tidyverse)
library(Article3Package)
```

# On gaussian dataset

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 3
s <- NormalSampler2(n = 100,
                    L = 1000,
                    K = 3,
                    prop.outlier = 0.2,
                    cs = cs)
expPCA <- PCAExperiment(s)
expPCA <- runExperiment(expPCA)
plot(expPCA) + 
      scale_x_continuous(limits = c(1,60))
```


```{r}
bootstrapCalibration(s = s, 
            method.K = K , 
            lambda.lfmmridge = 1e-5,
            exp.rep = 3)
```


# On logistic dataset

```{r}
c <- 0.6
K <- 6
s <- LogisticSampler(n = 100,
                    L = 1000,
                    K = K,
                    prop.outlier = 0.2,
                    c = c)
expPCA <- PCAExperiment(s)
expPCA <- runExperiment(expPCA)
plot(expPCA) + 
      scale_x_continuous(limits = c(1,60))
```

```{r}
bootstrapCalibration(s = s, 
            method.K = K, 
            lambda.lfmmridge = 1e-5,
            exp.rep = 3)
```
