---
title: "Validation and comparison on simulations"
author: "kevin caye"
date: "17 fevrier 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

```{r}
library(tidyverse)
library(Article3Package)
```

# On gaussian dataset
## Peut d'outlier

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 3
s <- NormalSampler2(n = 100,
                    L = 1000,
                    K = 3,
                    prop.outlier = 0.05,
                    cs = cs)

crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e-2, 
                        lambdas = c(1e-10, 1e0, 1e2, 1e40))
```

## Beaucoup d'outlier

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 3
s <- NormalSampler2(n = 100,
                    L = 1000,
                    K = 3,
                    prop.outlier = 0.2,
                    cs = cs)

crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e40, 
                        lambdas = c(1e-10, 1e0, 1e2, 1e40))
```

# On logistic dataset
## Peut d'outlier

```{r}
c <- 0.3
K <- 3
s <- LogisticSampler(n = 100,
                    L = 1000,
                    K = 3,
                    prop.outlier = 0.05,
                    c = c)

crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e-2, 
                        lambdas = c(1e-10, 1e0, 1e2, 1e40))
```

# On logistic dataset
## Beaucoup d'outlier

```{r}
c <- 0.6
K <- 6
s <- LogisticSampler(n = 100,
                    L = 1000,
                    K = 3,
                    prop.outlier = 0.15,
                    c = c)

crossValidationCriteria(s = s, 
                        method.K = 3, 
                        lambda.lfmmridge = 1e-2, 
                        lambdas = c(1e-10, 1e0, 1e2, 1e40))
```

```{r}
crossValidationCriteria(s = s, 
                        method.K = 3, 
                        lambda.lfmmridge = 1e2, 
                        lambdas = NULL)
```

# From 1000 genomes simulation

## easy

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 3
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
s <- FromTrueSampler(G.file = G.file,
                     n = NULL,
                     L = 1500,
                     K = K,
                     prop.outlier = 0.2,
                     rho = NULL,
                     cs = cs,
                     round = FALSE)

crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e-2, 
                        lambdas = c(1e-10, 1e0, 1e40))
```

```{r}
crossValidationCriteria(s = s, 
                        method.K = 2, 
                        lambda.lfmmridge = 1e-2, 
                        lambdas = NULL)
```


## hard

```{r}
K = 4
L = 2000
n = NULL
cs <- list()
cs[[3]] <- 0.6
# sample data
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
s <-  FromTrueSampler(G.file = G.file,
                       n = n,
                       L = L,
                       K = K,
                       prop.outlier = 0.30,
                       rho = NULL,
                       cs = cs,
                       round = FALSE)
seed <- sample.int(.Machine$integer.max, 1)
crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e3, 
                        lambdas = c(1e-5, 1e2,1e3, 1e4, 1e5, 1e34),
                        seed = seed,
                        cross.rep = 2)
```


# SSMPG 2016

## Case 2

```{r}
n <- NULL
L <- NULL
K = 3
s <- TrueSampler(G.file = "~/Projects/Data2016_2017/SSMPG2015/Case2/Case2.lfmm",
                 X.file = "~/Projects/Data2016_2017/SSMPG2015/Case2/Case2.env",
                 outlier.file = "~/Projects/Data2016_2017/SSMPG2015/Case2/Case2.outlier",
                 n = n,
                 L = L)

crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e3, 
                        lambdas = c(1e-5, 1e-1,1e1, 1e5),
                        cross.rep = 5)

```

```{r}
crossValidationCriteria(s = s, 
                        method.K = K, 
                        lambda.lfmmridge = 1e5, 
                        lambdas = NULL,
                        cross.rep = 5)
```

