---
title: "Lasso Ridge et lambda"
author: "kevin caye"
date: "24 janvier 2017"
output:
  html_notebook:
  toc: true
toc_float:
  collapsed: false
smooth_scroll: false
theme: journal
highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

```{r}
library(tidyverse)
library(Article3Package)
cl <- parallel::makeCluster(4)
doParallel::registerDoParallel(cl)
```


# normal dataset
```{r}

K = 6
L = 1000
n = 100
cs <- list()
cs[[3]] <- 0.9
# sample data
s <- NormalSampler(n = n,
                   L = L,
                   K = K,
                   prop.outlier = 0.2, 
                   sigma = 0.2,
                   c = NULL,
                   cs = cs)

LassoRidgeEtLambda(s, method.K = 4,
                   exp.rep = 1,
                   ridge.lambda.low = 1e-10,
                   ridge.lambda.medium = 1e0,
                   ridge.lambda.high = 1e10,
                   sparse.prop = 0.1, 
                   gif = TRUE)

```

# from 1000 genome dataset

## 10 % of outlier

```{r}

K = 3
L = 5000
n = NULL
cs <- list()
cs[[1]] <- 0.6
# sample data
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
s <-  FromTrueSampler(G.file = G.file,
                       n = n,
                       L = L,
                       K = K,
                       prop.outlier = 0.10,
                       rho = NULL,
                       cs = cs,
                       round = FALSE)

LassoRidgeEtLambda(s, method.K = 3,
                   exp.rep = 3,
                   ridge.lambda.low = 1e-5,
                   ridge.lambda.medium = 1e4,
                   ridge.lambda.high = 1e15,
                   sparse.prop = 0.05, 
                   gif = TRUE)
```

On a un exemple de simulation ou mettre un lambda trop fort n'est pas bon ! 


## 20 % of outlier

```{r}

K = 3
L = 5000
n = NULL
cs <- list()
cs[[3]] <- 0.6
# sample data
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
s <-  FromTrueSampler(G.file = G.file,
                       n = n,
                       L = L,
                       K = K,
                       prop.outlier = 0.30,
                       rho = NULL,
                       cs = cs,
                       round = FALSE)

LassoRidgeEtLambda(s, method.K = 4,
                   exp.rep = 3,
                   ridge.lambda.low = NULL,
                   ridge.lambda.medium = 1e4,
                   ridge.lambda.high = 1e15,
                   sparse.prop = 0.15, 
                   gif = TRUE)
```



# Ccl

Sur les données simulé a partir de vrai dataset ce n'est pas aussi évident que 
le lambda le plus petit soit le plus fort ! 

