---
title: "Validation and comparison on simulations with missing values"
author: "kevin caye"
date: "17 fevrier 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

```{r}
library(tidyverse)
library(Article3Package)
```

# On gaussian dataset

```{r}
cs <- c(0.8, 0.3, 0.0)
K <- 3
s <- NormalSampler2(n = 100,
                    L = 1000,
                    K = K,
                    prop.outlier = 0.10,
                    cs = cs) %>%
  MissingValueSampler(missing.prop = 0.5)

finalSimuValiation(s,
                   method.K = K,
                   lambda.lfmmridge = 1e0,
                   exp.rep = 2,
                   gif = FALSE,
                   comp.exp = FALSE,
                   fast.only = TRUE,
                   with.missing = TRUE)
```

# On gaussian dataset
## beaucoup d'outlier

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 3
s <- NormalSampler2(n = 100,
                    L = 1000,
                    K = K,
                    prop.outlier = 0.2,
                    cs = cs) %>%
  MissingValueSampler(missing.prop = 0.50)

finalSimuValiation(s,
                   method.K = K,
                   lambda.lfmmridge = 1e0,
                   exp.rep = 1,
                   gif = FALSE,
                   comp.exp = FALSE,
                   fast.only = TRUE,
                   with.missing = TRUE)
```

# From 1000 genomes simulation
## beaucoup d'outlier and valeurs manquantes

```{r}
cs <- c(0.6, 0.3, 0.0)
K <- 4
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
s <- FromTrueSampler(G.file = G.file,
                     n = NULL,
                     L = 10000,
                     K = K,
                     prop.outlier = 0.15,
                     rho = NULL,
                     cs = cs,
                     round = FALSE) %>%
  MissingValueSampler(missing.prop = 0.51)

finalSimuValiation(s,
                   method.K = K,
                   lambda.lfmmridge = 1e0,
                   exp.rep = 3,
                   gif = FALSE,
                   comp.exp = FALSE,
                   with.missing = TRUE,
                   fast.only = TRUE)
```

