---
title: "Validation de la méthode sur des dataset créer a partir du 1000 genomes"
author: "kevin caye"
date: "24 janvier 2017"
output: 
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

```{r}
library(tidyverse)
library(Article3Package)
```

# PCA on the dataset

1000 genome phase 3 chrm 22 only european and maf filtered at 0.03

```{r}
G.file <- "~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/European_Chrm22.rds"
G <- readRDS(G.file)

pca <- prcomp(G, center = TRUE, scale = FALSE)

plot(pca$sdev[1:100])
```


```{r}
indiv <- read_delim("~/Projects/Data2016_2017/1000Genomes/Phase3Chrm22/integrated_call_samples_v3.20130502.ALL.panel",
                    delim = "\t",
                    skip = 1,
                    col_names = FALSE)
names(indiv) <- c("sample", "pop", "super_pop","gender")
unique((indiv %>% dplyr::filter(super_pop == "EUR"))$pop)
```

There are 5 pops in europe.
Let's take K = 4

# Let's sample a dataset with association
```{r}
n <- NULL
L <- 2000
exp.rep <- 3
```

## We know K

### cor(X, U1) = 0.5 and 0.02 prop of outlier 

```{r}
Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.5,
  K = 4,
  prop.outlier = 0.02,
  # method
  method.K = 4,
  ridge.lambda = 0.1,
  sparse.prop = 0.1,
  gif = TRUE,
  # method
  exp.rep = exp.rep)
```


### cor(X, U1) = 0.7 and 0.1 prop of outlier 

```{r}

Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.7,
  K = 4,
  prop.outlier = 0.1,
  # method
  method.K = 4,
  ridge.lambda = 0.01,
  sparse.prop = 0.15,
  gif = TRUE,
  # method
  exp.rep = exp.rep)
```

## K is over estimated

### cor(X, U1) = 0.5 and 0.02 prop of outlier 

```{r}

Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.5,
  K = 4,
  prop.outlier = 0.02,
  # method
  method.K = 4 + 2,
  ridge.lambda = 0.01,
  sparse.prop = 0.10,
  gif = TRUE,
  # method
  exp.rep = exp.rep)
```


### cor(X, U1) = 0.7 and 0.1 prop of outlier 

```{r}
Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.7,
  K = 4,
  prop.outlier = 0.1,
  # method
  method.K = 4 + 2,
  ridge.lambda = 0.01,
  sparse.prop = 0.15,
  gif = TRUE,
  # method
  exp.rep = exp.rep)

```


## K is under estimated

### cor(X, U1) = 0.5 and 0.02 prop of outlier 

```{r}
Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.5,
  K = 4,
  prop.outlier = 0.02,
  # method
  method.K = 4 - 2,
  ridge.lambda = 0.01,
  sparse.prop = 0.10,
  gif = TRUE,
  # method
  exp.rep = exp.rep)
```


### cor(X, U1) = 0.7 and 0.1 prop of outlier 

```{r}
Validation_1000Genome( 
  # dataset
  n = n,
  L = L,
  c = 0.7,
  K = 4,
  prop.outlier = 0.1,
  # method
  method.K = 4 - 2,
  ridge.lambda = 0.01,
  sparse.prop = 0.15,
  gif = TRUE,
  # method
  exp.rep = exp.rep)

```



