---
title: "GWAS RIZ"
author: "kevin caye"
date: "13 mars 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

# Climate

## PCA
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/gwas_riz/climate/genotype.filtered.rds",
                 X.file = "../Data/gwas_riz/climate/tmaxPC2.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_pcaExp(s = s,
                       s.name = "climate gwas_riz",
                       cluster.nb = NULL,
                       save = TRUE, bypass = FALSE)

```

### plot
```{r}
exp <- retrieveExperiment(28)
plot(exp)
```


## CV
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/gwas_riz/climate/genotype.filtered.rds",
                 X.file = "../Data/gwas_riz/climate/tmaxPC2.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_cvExp(s = s,
                      s.name = "climate gwas_riz",
                      Ks = c(1,2,3,4, 5),
                      lambdas = c(1e-10, 1e0, 1e10, 1e30),
                      row.left.out.func = left.out.kfold(5),
                      col.left.out.func = left.out.sample(5, 0.2),
                      cluster.nb = 4,
                      save = TRUE, bypass = FALSE)

```

### Plot
```{r}
exp <- retrieveExperiment(38)
plot(exp$cv, color = "K")
plot(exp$cv, color = "lambda")
```


## LFMM runs
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/gwas_riz/climate/genotype.filtered.rds",
                 X.file = "../Data/gwas_riz/climate/tmaxPC2.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_runExp(s = s,
                       s.name = "climate gwas_riz",
                       Ks = c(2,3,4),
                       lambdas = c(1e-10, 1e-1, 1e10),
                       nb.rep = 1,
                       m = finalLfmmRdigeMethod(K = NULL,
                                                lambda = NULL,
                                                calibrate = FALSE),
                       cluster.nb = 6,
                       save = TRUE, bypass = FALSE)

```

### Plot
```{r}
exp <- retrieveExperiment(39)
plot(exp, threshold = 0.05, plot.type = "B")
plot(exp, threshold = 0.05, plot.type = "manhattan")
```

#### K = 3 and lambda = 1e-10

```{r}
toplot <- exp$df.res %>% 
  dplyr::filter(lambda == 1e10, K == 2, rep == 1) %>%
  mutate(chr = sub("_.*", "", col.name))
ggplot(toplot, aes(x = index, y = -log10(pvalue), color = chr)) +
  geom_point() +
  facet_grid(lambda ~ K, scales = "free")




```

```{r}
fdr.loc = fdrtool::fdrtool(toplot$score)

fdr.loc$pval
```

