---
title: "Article 3 figures"
author: "kevin caye"
date: "28 mars 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```


# numerical validation

## Method comparison

### run on krak
```{r}
require(ThesisRpackage)
G.file <- "~/Projects/Thesis/Data/1000Genomes/Phase3Chrm22/European_Chrm22.maf.05.rds"
exp <- Article3_MethodComparison(G.file,
                                 outlier.props = c(0.05, 0.1),
                                 n = NULL, L = 10000,
                                 K = 4,
                                 cs = c(0.6, 0.3, 0.0, 0.0),
                                 nb.rep = 10,
                                 fast.only = FALSE,
                                 cluster.nb = 4,
                                 save = TRUE, bypass = FALSE)
```

### plots

```{r}
exp <- retrieveExperiment(82)
```

```{r}
Article3_MethodComparison_plot(exp, plot.type = "pvalue.grid")
```

```{r}
Article3_MethodComparison_plot(exp, plot.type = "precision.recall")
```


## Method comparison with missing value

### run on krak

```{r}
require(ThesisRpackage)
G.file <- "~/Projects/Thesis/Data/1000Genomes/Phase3Chrm22/European_Chrm22.maf.05.rds"
s <- FromTrueSampler(G.file = G.file,
                     n = NULL,
                     L = 10000,
                     K = 4,
                     prop.outlier = 0.1,
                     rho = NULL,
                     cs = c(0.6, 0.3, 0.0, 0.0),
                     round = FALSE) %>%
  SparseMissingValueSampler(missing.prop = 0.1, missing.prop.by.loci = 0.5)
s.name <- make_description("FromTrueSampler", 
                           G.file = s$sampler$G.file,
                           prop.outlier = s$sampler$prop.outlier,
                           missing.prop = s$missing.prop,
                           missing.prop.by.loci = s$missing.prop.by.loci)
exp <- Article3_withMissingValueResults(s = s,
                                        s.name = s.name,
                                        nb.rep = 5,
                                        lambda = 1e-5,
                                        K = 4,
                                        cluster.nb = 4,
                                        fast.only = FALSE,
                                        save = TRUE, bypass = FALSE)
```

### plots

```{r}
exp <- retrieveExperiment(89)
```

```{r}
plot(exp)
```

