* 2017
** 2017-03 mars
*** 2017-03-10 Vendredi
**** DONE Changement de git pour la Biblio
     CLOSED: [2017-03-13 lun. 13:38]
   Entered on [2017-03-10 Ven 16:30]

   - [X] je backup sur le server kimsufy
   - [X] rm sur mon pc de bureau et cp dans ici :D
   - [X] mettre biblio.bib a la racode de Thesis
   - [X] le reste est private on fait un Gits sur kimsuffy et ce qui faut dans le
     makefile !!

     #+BEGIN_SRC bash
     git remote add origin cayek@176.31.253.205:/home/cayek/Gits/2017/Biblio.git
     #+END_SRC

**** TODO Migration des git article
   Entered on [2017-03-10 Ven 16:44]

   - [ ] rm sur mes poste
   - [ ] rm les gits et les liens vers ceux ci (mon site)
   - [X] les backup
     
     On va migrer tous ca au fure et à masure :D

*** 2017-03-13 lundi
**** DONE Data dir 
     CLOSED: [2017-03-13 lun. 16:11]
   Entered on [2017-03-13 lun. 13:49]

   For git annex see [[https://git-annex.branchable.com/direct_mode/][direct mode]]
   #+BEGIN_SRC bash
   git annex unannex
   #+END_SRC
**** GWAS RIZ
     Entered on [2017-03-13 lun. 16:08]

     [[file:Rnotebook/gwas_riz/gwas_riz.nb.html]]

***** TODO climate
      - K = 1 2 3
      - lambda différente values
      - avec X = tmaxPC2
      - on recalibre
      - lancer avec un genotype aléatoires 
        
      J'en sui a ecrire la fonction long_...

***** TODO flowering
      - K  1 2 3 4
      - lambda plusieurs valeurs ...
      - gerer les missing values dans X
**** Fin de journee
   Entered on [2017-03-13 lun. 18:01]

   Petit a petit je met en place le repo et bosse en même temps. Je vais migrer
   3Article au fur et a mesure.
***** TODO Questions
      - Comment on gere les images (git annex ? NON, ca bouge trop souvent)
      - Comment on gere les notebook ? (git annex ?NON idem)

        Faudrait pas faire grossir pour rien le repo...

   
