FIGURES = Figures/map.pdf Figures/manhattanplot.pdf \
Figures/figure5.pdf
EXPERIMENTS = Experiments/Results/TAIR9/err.K110.rep5.RData \
Experiments/Results/TAIR9/snpsTAIR9vepTAIR10.RData \
Experiments/Results/TAIR9/variogram.RData \
Experiments/Results/TAIR9/snmfK6.RData \
Experiments/Results/TAIR9/tess3K6.sigmaHeat1.5.RData
RMARKDOWNS = selectionScan.html selectionScanTESS3.html

include ../figures.mk
