// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// phenotypeWayReg_lm
Rcpp::List phenotypeWayReg_lm(const Eigen::Map<Eigen::MatrixXd>& Y, const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& CoVar);
RcppExport SEXP ThesisRpackage_phenotypeWayReg_lm(SEXP YSEXP, SEXP XSEXP, SEXP CoVarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type CoVar(CoVarSEXP);
    rcpp_result_gen = Rcpp::wrap(phenotypeWayReg_lm(Y, X, CoVar));
    return rcpp_result_gen;
END_RCPP
}
