---
title: "HGDP"
author: "kevin caye"
date: "16 mars 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```

# X_tmp
## PCA
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/Hgdp_Li/Hgdp_Li.rds",
                 X.file = "../Data/Hgdp_Li/X_tmp.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_pcaExp(s = s,
                       s.name = "Hgdp_Li X_tmp",
                       cluster.nb = NULL,
                       save = TRUE, bypass = FALSE)

```


## CV
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/Hgdp_Li/Hgdp_Li.rds",
                 X.file = "../Data/Hgdp_Li/X_tmp.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_cvExp(s = s,
                      s.name = "climate gwas_riz",
                      Ks = c(1,5,10,15, 20),
                      lambdas = c(1e-10, 1e0, 1e10),
                      row.left.out.func = left.out.kfold(5),
                      col.left.out.func = left.out.sample(5, 0.2),
                      cluster.nb = 4,
                      save = TRUE, bypass = FALSE)
```

## LFMM runs
### Run on krakenator

```{r}
library(ThesisRpackage)
s <- TrueSampler(G.file = "../Data/gwas_riz/climate/genotype.rds",
                 X.file = "../Data/gwas_riz/climate/tmaxPC2.rds",
                 outlier.file = NULL,
                 n = NULL,
                 L = NULL)
exp <- Article3_runExp(s = s,
                       s.name = "climate gwas_riz",
                       Ks = c(1,2,3),
                       lambdas = c(1e-10, 1e0, 1e10),
                       nb.rep = 1,
                       m = finalLfmmRdigeMethod(K = NULL,
                                                lambda = NULL,
                                                calibrate = TRUE),
                       cluster.nb = NULL,
                       save = TRUE, bypass = FALSE)
```
