# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Y ~ X_j + CoVar for all j
phenotypeWayReg_lm <- function(Y, X, CoVar) {
    .Call('ThesisRpackage_phenotypeWayReg_lm', PACKAGE = 'ThesisRpackage', Y, X, CoVar)
}

