---
title: "Tess3 with noisy coordinates"
author: "kevin caye"
date: "15 mars 2017"
output:
  html_notebook:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: journal
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE,
                      results = "hide", error = FALSE, fig.width = 10, fig.width = 10)
```


```{r}
library(tess3r)
library(ThesisRpackage)
```


# Perte de precision quand on bruite les coordonnées
```{r}
library(ThesisRpackage)
exp <- long_tess3_noisyCoord(ns = c(50, 500),
                             nsites.neutral = c(1.5 * 1e4,
                                                1.2 * 1e5),
                             m.neutral =  c(0.25 * 0.5 * 1e-6,
                                            0.25 * 1 * 1e-6,
                                            0.25 * 1.5 * 1e-6,
                                            0.25 * 2 * 1e-6,
                                            0.25 * 2.5 * 1e-6,
                                            0.25 * 3 * 1e-6,
                                            0.25 * 5 * 1e-6),
                             noise.signal = c(0.0, 0.2, 0.5,0.8, 1.0, 2.0, 3.0, 10.0),
                             nb.rep = 10,
                             compute.vario = FALSE,
                             cluster.nb = 4,
                             save = FALSE, bypass = TRUE)
```

## plot 
```{r}
exp <- retrieveExperiment(53)
exp$df.res <- exp$df.res %>%
  dplyr::filter(Fst.theorical < 0.7)
plot_tess3_noisyCoord(exp)
```


# Le garde fou : le variogram

```{r}
exp <- long_tess3_noisyCoord(n = 200,
                             cluster.nb = NULL,
                             nb.rep = 1,
                             noise.signal = c(0.0, 1.0, 3.0),
                             compute.vario = TRUE,
                             save = FALSE, bypass = TRUE)
plot_tess3_noisyCoord(exp)
```


