# safelist
branches:
  only:
  - deploy

sudo: required


before_script:
  - make docker_build
  - make docker_run
  - make pull_binary

script:
  - docker exec -it tess3_article make article

# see https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: Article/draft.pdf
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
